version: "3.9"

services:
  node1:
    build : .
    container_name: node01
    hostname: node01
    ports:
      # - "8485:8485"   # JournalNode RPC
      - "8480:8480"   # JournalNode HTTP UI
      - "9871:9870" # Namenode UI
      - "8081:8088" # Yarn UI
    command: bash /start-all.sh
    volumes:
    - ./jn1:/opt/data/journalnode
    - ./shared:/opt/hadoop/etc/hadoop
    - ./nn1:/shared/nn
    - ./start-all.sh:/start-all.sh
    - ./data:/data
    networks:
      - cluster-network

  node2:
    build : .
    container_name: node02
    hostname: node02
    ports:
      # - "8486:8485"   # JournalNode RPC
      - "8481:8480"   # JournalNode HTTP UI
      - "9872:9870"   # Namenode UI
      - "8082:8088"   # Yarn UI
    command: bash /start-all.sh
    volumes:
    - ./jn2:/opt/data/journalnode
    - ./shared:/opt/hadoop/etc/hadoop
    - ./nn2:/shared/nn
    - ./start-all.sh:/start-all.sh
    - ./data:/data
    networks:
      - cluster-network

  node3:
    build : .
    container_name: node03
    hostname: node03
    ports:
      # - "8487:8485"   # JournalNode RPC
      - "8482:8480"   # JournalNode HTTP UI
      - "9864:9864"   # DataNode HTTP UI
      # - "9873:9870"
      # - "8083:8088"
    command: bash /start-all.sh
    volumes:
    - ./jn3:/opt/data/journalnode
    - ./shared:/opt/hadoop/etc/hadoop
    - ./dn3:/shared/dn
    - ./start-all.sh:/start-all.sh
    - ./data:/data
    networks:
      - cluster-network

  node4:
    build : .
    container_name: node04
    hostname: node04
    ports:
      # - "8488:8485"
      - "9865:9864"   # DataNode HTTP UI
      # - "9874:9870"
      # - "8084:8088"
    command: bash /start-all.sh
    volumes:
    - ./dn4:/shared/dn
    - ./shared:/opt/hadoop/etc/hadoop
    - ./start-all.sh:/start-all.sh
    - ./data:/data
    networks:
      - cluster-network

  node5:
    build : .
    container_name: node05
    hostname: node05
    ports:
      # - "8489:8485"
      - "9866:9864"   # DataNode HTTP UI
      # - "9875:9870"
      # - "8085:8088"
    command: bash /start-all.sh
    volumes:
    - ./dn5:/shared/dn
    - ./shared:/opt/hadoop/etc/hadoop
    - ./start-all.sh:/start-all.sh
    - ./data:/data
    networks:
      - cluster-network

networks:
  cluster-network:
    driver: bridge